# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 2.1"
gem 'rspec'
gem "sinatra-reloader", "~> 1.0"
